defaults:
  - /base_configs/dataModule_config.yaml@_here_ 
  - _self_
# make sure _self_ is in the end as it means to inherent last from this file meaning overwriting the inhereted values if needed

global_batch_size: 32
# add more as required
dataModuleType : Real # can  be Mock or Real as of now.
msc_config : "msc_config_s3.yaml"
data_paths_config_file: "data_paths_config.yaml"
object_storage_cache_path : "../object_storage_cache"
streaming : True # has to True or False