train:
  subcategories:
    news_data:
      weight: 0.7
      paths:
        - path: "msc://my_test_data/my-gpt_text_document"
          weight: 0.6
        - path: "msc://my_test_data/my-gpt_text_document"
          weight: 0.4
    social_media:
      weight: 0.3
      paths:
        - path: "msc://my_test_data/my-gpt_text_document"
          weight: 1

validation:
  subcategories:
    small_val_set:
      weight: 1.0
      paths:
        - path: "msc://my_test_data/my-gpt_text_document"
          weight: 1.0

test:
  subcategories:
    small_test_set:
      weight: 1.0
      paths:
        - path: "msc://my_test_data/my-gpt_text_document"
          weight: 1.0

